/**
 * All 16 user roles in the BloodBank system.
 * Realm roles: SUPER_ADMIN, REGIONAL_ADMIN, SYSTEM_ADMIN, AUDITOR
 * Client roles: BRANCH_ADMIN, BRANCH_MANAGER, DOCTOR, LAB_TECHNICIAN,
 *   PHLEBOTOMIST, NURSE, INVENTORY_MANAGER, BILLING_CLERK,
 *   CAMP_COORDINATOR, RECEPTIONIST, HOSPITAL_USER, DONOR
 */
export enum Role {
  // Realm roles
  SUPER_ADMIN = 'SUPER_ADMIN',
  REGIONAL_ADMIN = 'REGIONAL_ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  AUDITOR = 'AUDITOR',

  // Client roles
  BRANCH_ADMIN = 'BRANCH_ADMIN',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  DOCTOR = 'DOCTOR',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  PHLEBOTOMIST = 'PHLEBOTOMIST',
  NURSE = 'NURSE',
  INVENTORY_MANAGER = 'INVENTORY_MANAGER',
  BILLING_CLERK = 'BILLING_CLERK',
  CAMP_COORDINATOR = 'CAMP_COORDINATOR',
  RECEPTIONIST = 'RECEPTIONIST',
  HOSPITAL_USER = 'HOSPITAL_USER',
  DONOR = 'DONOR',
}

/** Staff roles — all roles except HOSPITAL_USER and DONOR */
export const STAFF_ROLES: Role[] = [
  Role.SUPER_ADMIN,
  Role.REGIONAL_ADMIN,
  Role.SYSTEM_ADMIN,
  Role.AUDITOR,
  Role.BRANCH_ADMIN,
  Role.BRANCH_MANAGER,
  Role.DOCTOR,
  Role.LAB_TECHNICIAN,
  Role.PHLEBOTOMIST,
  Role.NURSE,
  Role.INVENTORY_MANAGER,
  Role.BILLING_CLERK,
  Role.CAMP_COORDINATOR,
  Role.RECEPTIONIST,
];

/** Realm-level admin roles */
export const REALM_ROLES: Role[] = [
  Role.SUPER_ADMIN,
  Role.REGIONAL_ADMIN,
  Role.SYSTEM_ADMIN,
  Role.AUDITOR,
];
