stream_over_http_enabled: true

server:
  http_listen_port: 3200
  grpc_listen_port: 9095
  log_level: info

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09

query_scheduler:
  max_outstanding_requests_per_tenant: 2000

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
    zipkin:
      endpoint: 0.0.0.0:9411

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s

compactor:
  compaction_window: 1h
  max_block_bytes: 100_000_000
  block_retention: 72h
  compacted_block_retention: 10m
  compaction_cycle: 30s

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: bloodbank
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

storage:
  trace:
    backend: local
    block:
      bloom_filter_false_positive: 0.05
      index_downsample_bytes: 1000
      encoding: zstd
    wal:
      path: /var/tempo/wal
      encoding: snappy
    local:
      path: /var/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
      generate_native_histograms: both
